spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_ADDRESS}/ddd_attendance?useUnicode=yes&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
jwt:
  secret: ${JWT_SECRET}
  expires: ${JWT_EXPIRES}
event:
  late-diff-minute: ${DDD_LATE_DIFF_MINUTE}
  absent-diff-minute: ${DDD_ABSENT_DIFF_MINUTE}